/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 *  License, v. 2.0. If a copy of the MPL was not distributed with this
 *  file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

package fr.nicopico.petitboutiste.ui

object UiTags {
    const val INPUT_TYPE_TOGGLE = "INPUT_TYPE_TOGGLE"
    const val DATA_INPUT = "DATA_INPUT"

    const val BYTE_GROUP_DEFINITIONS = "BYTE_GROUP_DEFINITIONS"
    const val BYTE_GROUP_DEFINITIONS_TOGGLE_REPRESENTATION_FORM = "BYTE_GROUP_DEFINITIONS_TOGGLE_REPRESENTATION_FORM"
    const val BYTE_GROUP_DEFINITIONS_EXPORT_VALUES = "BYTE_GROUP_DEFINITIONS_EXPORT_VALUES"
    const val BYTE_GROUP_DEFINITIONS_ADD_DEFINITION = "BYTE_GROUP_DEFINITIONS_ADD_DEFINITION"

    const val BYTE_GROUP_DEFINITIONS_ITEM = "BYTE_GROUP_DEFINITIONS_ITEM"
    const val BYTE_GROUP_DEFINITIONS_ITEM_LABEL = "BYTE_GROUP_DEFINITIONS_ITEM_LABEL"
    const val BYTE_GROUP_DEFINITIONS_ITEM_RANGE = "BYTE_GROUP_DEFINITIONS_ITEM_RANGE"
    const val BYTE_GROUP_DEFINITIONS_ITEM_ERROR = "BYTE_GROUP_DEFINITIONS_ITEM_ERROR"
    const val BYTE_GROUP_DEFINITIONS_ITEM_RENDER = "BYTE_GROUP_DEFINITIONS_ITEM_RENDER"
    const val BYTE_GROUP_DEFINITIONS_ITEM_REMOVE = "BYTE_GROUP_DEFINITIONS_ITEM_REMOVE"
    const val BYTE_GROUP_DEFINITIONS_ITEM_TOGGLE_FORM = "BYTE_GROUP_DEFINITIONS_ITEM_TOGGLE_FORM"

    const val BYTE_GROUP_DEFINITIONS_ITEM_FORM = "BYTE_GROUP_DEFINITIONS_ITEM_FORM"
    const val BYTE_GROUP_DEFINITIONS_ITEM_FORM_INPUT_NAME = "BYTE_GROUP_DEFINITIONS_ITEM_FORM_INPUT_NAME"
    const val BYTE_GROUP_DEFINITIONS_ITEM_FORM_INPUT_START = "BYTE_GROUP_DEFINITIONS_ITEM_FORM_INPUT_START"
    const val BYTE_GROUP_DEFINITIONS_ITEM_FORM_INPUT_END = "BYTE_GROUP_DEFINITIONS_ITEM_FORM_INPUT_END"
    const val BYTE_GROUP_DEFINITIONS_ITEM_REPRESENTATION_FORM = "BYTE_GROUP_DEFINITIONS_ITEM_REPRESENTATION_FORM"
    const val BYTE_GROUP_DEFINITIONS_ITEM_FORM_SAVE = "BYTE_GROUP_DEFINITIONS_ITEM_FORM_SAVE"

    const val BYTE_GROUP_REPRESENTATION_FORM = "BYTE_GROUP_REPRESENTATION_FORM"
    const val BYTE_GROUP_REPRESENTATION_FORM_DATA_RENDERER = "BYTE_GROUP_REPRESENTATION_FORM_DATA_RENDERER"
    const val BYTE_GROUP_REPRESENTATION_FORM_ARGUMENTS_FORM = "BYTE_GROUP_REPRESENTATION_FORM_ARGUMENTS_FORM"
    const val BYTE_GROUP_REPRESENTATION_RENDER = "BYTE_GROUP_REPRESENTATION_RENDER"
    const val BYTE_GROUP_REPRESENTATION_RENDER_COPY_TO_CLIPBOARD = "BYTE_GROUP_REPRESENTATION_RENDER_COPY_TO_CLIPBOARD"
    const val BYTE_GROUP_REPRESENTATION_RENDER_OPEN_NEW_TAB = "BYTE_GROUP_REPRESENTATION_RENDER_OPEN_NEW_TAB"

    const val SNACKBAR = "SNACKBAR"
    const val SCRATCHPAD = "SCRATCHPAD"
}
