name: Validate Pull Request

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    name: Build and Check quality
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: '21'
          cache: 'gradle'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Assemble the app
        run: ./gradlew assemble -PappVersion=1.0.0

      # Quality gate
      - parallel:
          - name: Run tests with coverage
            run: ./gradlew desktopTest koverXmlReport -PappVersion=1.0.0
            env:
              SCREENSHOT_DIR: build/screenshots

          - name: Check code quality
            run: ./gradlew --no-daemon detektDesktopMain -PappVersion=1.0.0

          - name: Check licenses
            run: ./gradlew --no-daemon licensee -PappVersion=1.0.0

          - name: Check compose stability
            run: ./gradlew --no-daemon stabilityCheck -PappVersion=1.0.0

      # Result publication
      - parallel:
          - name: Attach coverage report to PR
            uses: mi-kas/kover-report@v1
            if: always()
            with:
              path: |
                ${{ github.workspace }}/composeApp/build/reports/kover/report.xml
              title: Code Coverage
              update-comment: true

          - name: Attach Unit-Test report to PR
            uses: mikepenz/action-junit-report@v4
            if: always()
            with:
              report_paths: 'composeApp/build/test-results/desktopTest/**.xml'

          - name: Attach UI tests screenshots to PR
            if: always()
            uses: opengisch/comment-pr-with-images@upload_only
            with:
              images: composeApp/build/screenshots/**.png
              custom_attachment_msg: "UI Tests screenshots"
